### ISSUE TITLE
Unexpected server response: 524

### ISSUE THREAD

**Issue by OctipusV** [lavacord/Lavacord#107]
Started experiencing this issue recently, and I'm guessing it's caused on the lavalink server-side and not on the discord client-side as nothing has been changed on my part.  Any potential fixes to this problem? Thanks.

**Comment by PapiOphidian** [comment]
https://http.cat/504

**Comment by PapiOphidian** [comment]
HTTP 524 is a CloudFlare specific timeout error. Seems like connection to CF is fine, but host machine didn't respond in time
