### ISSUE TITLE
Nodes is not iterable (told in the server)

### ISSUE THREAD

**Issue by jj2neat** [lavacord/Lavacord#2]
(node:3904) UnhandledPromiseRejectionWarning: TypeError: nodes is not iterable
    at new Manager (C:\Users\jnsho\node_modules\lavacord\dist\lib\Manager.js:17:28)

nodes =

[
  {
    name: 'Node Test #1',
    host: 'localhost',
    port: 2333,
    password: 'youshallpass'
  }
]

**Comment by jj2neat** [comment]
(documentation was wrong) told me to do:

new manager(client, nodes, {})
turns out it was
new manager(nodes, client, {})

**Comment by MrJacz** [comment]
there is no client so both are wrong
its `new Manager(nodes, options)`
so `new Manager(nodes, { user: "bot user id", send: () => { // do stuff here }; });` which i have explained in discord
