### ISSUE TITLE
Idea: Have a region property on LavalinkNode for sorting.

### ISSUE THREAD

**Issue by Gaeta** [lavacord/Lavacord#21]
What about a function where we can we enter a region like "eu" and it will pick the best eu feature.

Or just a variable we can put on the node like "eu" or "us" so we can do a filter?

**Comment by MrJacz** [comment]
I'll think about it

**Comment by Gaeta** [comment]
what about a extra pram with `{}` in it so we can leave extra data inside like shuffle etc without it getting deleted?

**Comment by MrJacz** [comment]
@Dream-cake could you elaborate?

**Comment by Gaeta** [comment]
Example the `state` variable in player but instead have an extra one named `extra` where the user can store extra dataa.

```json
{
...
state: {volume: 0, ...},
extra: {}
}
```

**Comment by Gaeta** [comment]
also this extra could be used for nodes to store extra data about them like region etc

**Comment by MrJacz** [comment]
The state idea wont happen, thats not what state is used for. its actually something lavalink sends over and I just add the volume to it, As i needed somewhere to set it

**Comment by pedrofracassi** [comment]
I'm pretty sure he isn't talking about modifying `state`, but adding an `extra` on the same level instead, so we can store metadata about the node

**Comment by Skye-31** [comment]
I agree, a state implies something temporary, which a region wouldn't fit into.

**Comment by MrJacz** [comment]
May I suggest using the `id` property?
if there is a good reason why that doesn't work, I'll add a region property.

**Comment by Skye-31** [comment]
I could see a use case in large bots where nodes are dynamically created and destroyed by a load balancer when required, and an ID could just be a numerical value, or something random, and so that could not be relied on, the region however, would be the same.

I think in general, having a property that allows us to set extra information would be useful.

**Comment by MrJacz** [comment]
@BennyDiscord Feel free to pr it,

**Comment by Skye-31** [comment]
This is now available in #52
