### ISSUE TITLE
A weird issue

### ISSUE THREAD

**Issue by thrace19** [lavacord/Lavacord#39]
```js
(node:5867) UnhandledPromiseRejectionWarning: Error: No available websocket connection for selected node.
```

**Comment by en-you** [comment]
Your code must have problem.

Come to following Discord server and solve it
https://discord.gg/wXrjZmV

**Comment by MrJacz** [comment]
@inhydrox hey sorry, I didnt see this. For errors and better support I suggest going to the discord server, the invite is https://discord.gg/wXrjZmV

It just allows for us to give you better support and free up people's emails.
But just having a look, it looks like you need to call `Manager#connect`
